### ISSUE TITLE
I would love to see a NuGet package with this.

### ISSUE THREAD

**Issue by bojingo** [codemillmatt/XamFormsVMNav#2]
I pulled this into one of my projects as many of the existing frameworks seemed a little "heavy" for a Xamarin Forms app. Really like the simple focus on navigation.

However, I will have a second project that will need this so having a community NuGet package would be convenient so I don't have to either copy code around (yuck) or manage my own package (hassle).

**Comment by codemillmatt** [comment]
I agree - it has been on my list to component-ize it and NuGet-ize it for a while. I'll bump it up in the priority.

**Comment by codemillmatt** [comment]
It was a while coming @bojingo - but here it is:

[Nuget](https://www.nuget.org/packages/CodeMill.VMFirstNav/)
[Repo](https://github.com/codemillmatt/codemill.vmfirstnav)

Please open any issues should you find a problem (or want an enhancement).
